name: auth_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

dependencies:
  app_domain:
    path: ../../../app_domain
  pocketbase: ^0.23.0
  equatable: ^2.0.5
  rxdart: ^0.28.0
  json_annotation: ^4.9.0

environment:
  sdk: ^3.5.0

dev_dependencies:
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
