name: app_repository
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

dependencies:
  app_domain:
    path: ../../../app_domain
  pocketbase: ^0.23.0
  equatable: ^2.0.5

environment:
  sdk: ^3.5.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0
